### ISSUE TITLE
Updated games-engines/unity3d

### ISSUE THREAD

**Issue by redchillipadi** [mradermaxlol/maxik-ebuilds#10]
I am interested in keeping games-engines/unity3d up to date. For a few months now I have been maintaining the ebuild [on my github](https://github.com/redchillipadi/ebuild-overlay)

**Comment by mradermaxlol** [comment]
@redchillipadi umm, eh... So what do you want from me? :) Keep that stuff updated in your overlay, no drama. I don't think I'll be in the Gentoo world anytime soon, so feel free to "fork" and edit/maintain as many ebuilds as you want. I don't care about the "author thingie", although AFAIK the GPL license makes pointing out the original author a must, well... Once again, I don't care about that, so do whatever you want.

**Comment by redchillipadi** [comment]
I was not sure whether you wanted pull requests to keep your overlay current also. No worries, I will just keep unity up to date on my site. Thanks for getting the initial ebuild working.
